services:
  gistdb:
    build: .
    ports:
      - "8085:8085"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - JWT_PUBLIC_KEY=${JWT_PUBLIC_KEY}
    networks:
        - tunnel-net

networks:
  tunnel-net:
    external: true
